### ISSUE TITLE
Add -pthread flag to compile options

### ISSUE THREAD

**Issue by ga2k** [vitaut/modules#17]
Hey, this is great. But I need to add -pthread to the compile options for the modules. I don't know how I can add this flag, so I just modify your code to include that flag.

Is there a way I can pass the flag to modules.cmake? I'm new to this CMake world.

Cheers,
Geoff.

**Comment by vitaut** [comment]
You can do this via usual CMake means such as the Threads CMake module, see https://stackoverflow.com/a/39547577/471164.
